### PR TITLE
Sync the editors on switch if change zeros out original change

### LINKED ISSUE #711: Switch to html misses text change if the change bring the content back to origin
### Expected
Removing changes and switching to html mode should mirror the new state of the content.

### Observed
The text in html mode is still the one that includes changes.

### Reproduced
1. Run the demo app and add some characters at the beginning of text
2. Switch to html mode
3. Switch back to visual
4. Remove/delete the characters added in step 1
5. Switch to html mode and observe the text still having the chars from step 1

This seems to be a regression introduced with https://github.com/wordpress-mobile/AztecEditor-Android/pull/704

#### Tested
Nexus 5X on Android 7.1.2 with app version efd43ed795f4c321590f1f7ff720eb1c4d4390a7

### PR DESCRIPTION
**Pull request by hypest**
### Fix #711 

This PR add another check for when switching between visual and html mode to have the editors sync their content between them if an editor has been modified since the last time a switch happened. That way, a change that effectively cancels out any change compared to the originally loaded content will be mirrored to the other editor as well.

### Test
1. Run the demo app and add some characters at the beginning of text
2. Switch to html mode
3. Switch back to visual
4. Remove/delete the characters added in step 1
5. Switch to html mode and observe the chars from Step 1 having been removed from the html mode too

### CODE REVIEW

File: aztec/src/main/kotlin/org/wordpress/aztec/toolbar/AztecToolbar.kt [hunk 1]
```diff
@@ -561,22 +572,37 @@ class AztecToolbar : FrameLayout, IAztecToolbar, OnMenuItemClickListener {
         }
     }
 
+    private fun syncEditorFromSource() {
```
Comment (daniloercoli) [inline aztec/src/main/kotlin/org/wordpress/aztec/toolbar/AztecToolbar.kt]: It seems to me that this method reads the content from the Visual editor, and in case of changes put the content into the HTML editor. 
If so, should we rename this method in `syncSourceEditorFromVisual`?

File: aztec/src/main/kotlin/org/wordpress/aztec/toolbar/AztecToolbar.kt [hunk 2]
```diff
@@ -561,22 +572,37 @@ class AztecToolbar : FrameLayout, IAztecToolbar, OnMenuItemClickListener {
...
+        val editorHtml = editor!!.toPlainHtml(true)
+        val sha256 = AztecText.calculateSHA256(editorHtml)
+        if (editor!!.hasChanges() != NO_CHANGES || !Arrays.equals(editorContentParsedSHA256LastSwitch, sha256)) {
+            sourceEditor!!.displayStyledAndFormattedHtml(editorHtml)
+        }
+        editorContentParsedSHA256LastSwitch = sha256
+    }
+
+    private fun syncSourceFromEditor() {
```
Comment (daniloercoli) [inline aztec/src/main/kotlin/org/wordpress/aztec/toolbar/AztecToolbar.kt]: Same comment of above, should we rename to `synchVisualEditorFromSourceEditor`?

File: aztec/src/main/kotlin/org/wordpress/aztec/toolbar/AztecToolbar.kt (hunk 1 above)
Comment (hypest) [reply aztec/src/main/kotlin/org/wordpress/aztec/toolbar/AztecToolbar.kt]: Indeed, binary is hard! Will swap the names, good eyes!

**Comment by hypest** [comment]
I've exchanged the method names with a973449 @daniloercoli , ready for another pass, thanks!

**Comment by daniloercoli** [comment]
Cool! :shipit:
