### PR TITLE
Fix order of multiple media

### LINKED ISSUE #627: Multiple images are added in incorrect order
Start with a blank demo app, and add > 3 pictures in a row.
The 3rd picture is added to the editor between the 1st and the 2nd.

The problem lies in `insertMedia` in `LineBlockFormatter`.
Ref: https://github.com/wordpress-mobile/WordPress-Android/issues/7199

### PR DESCRIPTION
**Pull request by daniloercoli**
This PR fixes #627 by making sure the cursor is correctly placed in the editor when media is added to it.

Before this PR there was an issue where starting from an empty editor, and adding 2 media to it, resulting in a cursor placed between the 1st and the 2nd picture. Then if you added a 3rd picture to the editor, it was being added in between the two before. As reported in `wp-android`.

**Before this PR**
-*Insert first media*
`newSelection` = 1 and text length=1 (correct, only one item in the editor, no new line at the end).

-*Insert second media*
`newSelection` = 2 1 and text length=3 (incorrect, the cursor is being placed in between the pictures). newSelection should be 3.

After this PR `newSelection` is being calculated correctly.

### CODE REVIEW

File: aztec/src/main/kotlin/org/wordpress/aztec/formatting/LineBlockFormatter.kt [hunk 1]
```diff
@@ -172,10 +172,17 @@ class LineBlockFormatter(editor: AztecText) : AztecFormatter(editor) {
                 Spanned.SPAN_EXCLUSIVE_EXCLUSIVE
         )
 
+        // We need to be sure the cursor is placed correctly after media insertion
+        // Note that media has '\n' around them when needed
+        val isLastItem = if (selectionEnd == EndOfBufferMarkerAdder.safeLength(editor)) { true } else false
```
Comment (0nko) [inline aztec/src/main/kotlin/org/wordpress/aztec/formatting/LineBlockFormatter.kt]: Nitpick - no need for the curly braces.

**Comment by 0nko** [comment]
:shipit:
