### PR TITLE
Fix for 'PARAGRAPH span must start at paragraph boundary'

### LINKED ISSUE #501: Cut&Paste Crash - RuntimeException: PARAGRAPH span must start at paragraph boundary
I had the editor with a long text in it. Different styles were applied to the text.
I selected a word and then pasted other chunk of text previously copied in the clipboard.

**Tested on Nexus 5X Android 7**

```
java.lang.RuntimeException: PARAGRAPH span must start at paragraph boundary
 at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:687)
 at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
 at org.wordpress.aztec.util.SpanWrapper.setFlags(SpanWrapper.kt:20)
 at org.wordpress.aztec.AztecParser.markBlockElementsAsParagraphs(AztecParser.kt:255)
 at org.wordpress.aztec.AztecParser.fromHtml(AztecParser.kt:45)
 at org.wordpress.aztec.AztecText.fromHtml(AztecText.kt:737)
 at org.wordpress.aztec.AztecText.paste(AztecText.kt:1053)
 at org.wordpress.aztec.AztecText.onTextContextMenuItem(AztecText.kt:964)
 at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:3793)
 at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2301)
 at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:88)
 at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
 at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
 at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
 at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
 at com.android.internal.view.FloatingActionMode$4.onMenuItemClick(FloatingActionMode.java:114)
 at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$3.onClick(FloatingToolbar.java:394)
 at android.view.View.performClick(View.java:5637)
 at android.view.View$PerformClick.run(View.java:22429)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6121)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

Related to https://github.com/wordpress-mobile/AztecEditor-Android/issues/481 ?

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #501 and #481 by not adding new lines to empty spans.

**To Test**
Paste the following HTML code in the visual editor
```
<p></p><span>[caption]</span>
```
It should not crash the app.

There is a change that the same problem can occur for other tags that are not "caption" or "img", but I wan't able to reproduce on those other tags.

### CODE REVIEW

**Comment by 0nko** [comment]
It seems this does not fix the issue entirely. Pasting the full text from https://fabric.io/automattic/android/apps/org.wordpress.android/issues/59a7e418be077a4dcce162ef?time=last-thirty-days still causes a crash.

Maybe we should add a condition check before applying `SPAN_PARAGRAPH` flag in `AztecParser`.

**Comment by daniloercoli** [comment]
Right, it's probably best to add a condition check berore applying `SPAN_PARAGRAPH `.

For reference this is a test code to use to test this other problem:
`<p></p> <span>  [caption ]</span>Test`

File: aztec/src/main/kotlin/org/wordpress/aztec/util/SpanWrapper.kt [hunk 1]
```diff
@@ -17,7 +23,18 @@ class SpanWrapper<T>(var spannable: Spannable, var span: T) {
 
     var flags: Int
         get() { return spannable.getSpanFlags(span) }
-        set(flags) { spannable.setSpan(span, start, end, flags) }
+        set(flags) {
+            // Do not set the span if it's a PARAGRAPH that doesn't start at paragraph boundary
+            // Copied from SpannableStringBuilder that throws an exception in this case.
+            val flagsStart = flags and START_MASK shr START_SHIFT
+            if (!isInvalidParagraph(start, flagsStart)) {
```
Comment (0nko) [inline aztec/src/main/kotlin/org/wordpress/aztec/util/SpanWrapper.kt]: Since we're checking for the correct start bound of a paragraph, should we also check for the correct end (the last char is a newline or end == text.length)?

**Comment by 0nko** [comment]
Would the system Log messages show up anywhere if the app doesn't crash? I know you can log caught exceptions in Crashlytics but we'd be avoiding that here.

File: aztec/src/main/kotlin/org/wordpress/aztec/util/SpanWrapper.kt (hunk 1 above)
Comment (daniloercoli) [reply aztec/src/main/kotlin/org/wordpress/aztec/util/SpanWrapper.kt]: Right, i've omitted that check on purpose, since we're not seeing crashes for it, but now that I think more on it I agree with you, better to have that check in the code.

**Comment by daniloercoli** [comment]
Nope, system Logs are not shown in wp-android app logs. We should use our Logging library `AppLog`, already available in Utils, if we want to add them to the main app log.

Btw, this is ready for another round.

**Comment by 0nko** [comment]
Thanks. It looks good 👍. I'll merge this one and we can add logging in another PR, I think it could be useful.

:shipit:
