### PR TITLE
Make sure big instance data is not stored to the default state/bundle

### LINKED ISSUE #561: Large text blocks make the app crash
### Expected
AztecText should handle a big piece of text

### Observed
Pasting a 1mb block of text twice at the end of the demo app, (sample content [used here](http://www.sample-videos.com/text/Sample-text-file-1000kb.txt)) then 
scrolling up and down, adding some text on the keyboard you’ll see that it lags a lot, but it works and keeps formatted text as you enter it, scroll up/down and it will be kept. It even works well when rotating the device as well.

At some point, if you go all the way down and tap on the last position (right of the last character) it will crash with this stacktrace:

```
12-05 16:25:08.962 6516-6516/org.wordpress.aztec D/AndroidRuntime: Shutting down VM
12-05 16:25:08.964 6516-6516/org.wordpress.aztec E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: org.wordpress.aztec, PID: 6516
                                                                   java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1160676 bytes
                                                                       at android.view.autofill.AutofillManager.updateSessionLocked(AutofillManager.java:884)
                                                                       at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:467)
                                                                       at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:443)
                                                                       at android.view.View.notifyEnterOrExitForAutoFillIfNeeded(View.java:6942)
                                                                       at android.view.View.performClick(View.java:6264)
                                                                       at android.view.View$PerformClick.run(View.java:24697)
                                                                       at android.os.Handler.handleCallback(Handler.java:789)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                       at android.os.Looper.loop(Looper.java:164)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                    Caused by: android.os.TransactionTooLargeException: data parcel size 1160676 bytes
                                                                       at android.os.BinderProxy.transactNative(Native Method)
                                                                       at android.os.BinderProxy.transact(Binder.java:748)
                                                                       at android.view.autofill.IAutoFillManager$Stub$Proxy.updateSession(IAutoFillManager.java:452)
                                                                       at android.view.autofill.AutofillManager.updateSessionLocked(AutofillManager.java:879)
                                                                       at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:467) 
                                                                       at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:443) 
                                                                       at android.view.View.notifyEnterOrExitForAutoFillIfNeeded(View.java:6942) 
                                                                       at android.view.View.performClick(View.java:6264) 
                                                                       at android.view.View$PerformClick.run(View.java:24697) 
                                                                       at android.os.Handler.handleCallback(Handler.java:789) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                       at android.os.Looper.loop(Looper.java:164) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
12-05 16:25:08.968 914-1311/? W/ActivityManager:   Force finishing activity org.wordpress.aztec/.demo.MainActivity
```

### Reproduced
1. start the demo app
2. paste a big block of text, 2mb
3. scroll up and down, rotate, insert some text in the middle and give it some format
4. at some point, scroll all the way down and try to position the cursor at the very end of the content
5. see the crash happen

#### Tested
[Google Pixel] on [Android 8.0]

### PR DESCRIPTION
**Pull request by daniloercoli**
### Fix
In order to fix #561 we've introduced the ability to save big instance data in files, instead of saving them to the default state/bundle. See #641.
Unfortunately we were still saving part of the data (the content) to the default bundle (`superState` variable) and still having TTL exception in crash reports.

We also needed to do the same for the HTML raw editor (`SourceViewEditText`), but we missed it.  In the demo app I see the html editor instantiated even if not active. Not sure if wp-android always instantiate it, or keep it off until the user switch to it. In the doubt I replicated the same fix there.

### Test
See steps in #641

### Review
@hypest @0nko

### CODE REVIEW

File: aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt [hunk 1]
```diff
@@ -568,16 +563,20 @@ class AztecText : AppCompatEditText, TextWatcher, UnknownHtmlSpan.OnUnknownHtmlT
...
-        writeTempInstance(INPUT_LAST_KEY, history.inputLast, bundle)
+        InstanceStateUtils.writeTempInstance(context, externalLogger, INPUT_LAST_KEY, history.inputLast, bundle)
         bundle.putInt(VISIBILITY_KEY, visibility)
-        writeTempInstance(RETAINED_HTML_KEY, toHtml(false), bundle)
+        InstanceStateUtils.writeTempInstance(context, externalLogger, RETAINED_HTML_KEY, toHtml(false), bundle)
         bundle.putInt(SELECTION_START_KEY, selectionStart)
         bundle.putInt(SELECTION_END_KEY, selectionEnd)
+        // disable text listeners and clear the content, otherwise TTL Exception may occur again
+        disableTextChangedListener()
+        setText("")
```
Comment (0nko) [inline aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt]: This line causes loss of text when I minimize and immediately open the app.

File: aztec/src/main/kotlin/org/wordpress/aztec/source/SourceViewEditText.kt [hunk 2]
```diff
@@ -84,12 +88,16 @@ class SourceViewEditText : android.support.v7.widget.AppCompatEditText, TextWatc
...
         val customState = savedState.state
         visibility = customState.getInt("visibility")
+        val retainedContent = InstanceStateUtils.readAndPurgeTempInstance<String>(RETAINED_CONTENT_KEY, "", savedState.state)
+        setText(retainedContent)
     }
 
     override fun onSaveInstanceState(): Parcelable {
+        val bundle = Bundle()
+        InstanceStateUtils.writeTempInstance(context, null, RETAINED_CONTENT_KEY, text.toString(), bundle)
+        setText("")
```
Comment (0nko) [inline aztec/src/main/kotlin/org/wordpress/aztec/source/SourceViewEditText.kt]: Same as in `AztecText`, this causes loss of text.

Comment (daniloercoli) [reply aztec/src/main/kotlin/org/wordpress/aztec/source/SourceViewEditText.kt]: Ahh I see it. I had tested with rotating the device, and enabling to not keep the activity and didn't notice the issue. 
The underlying problem (`onRestoreInstanceState` that is not called) was not surfaced in the previous version of the code since the component was still retaining the content internally and saving the data in `superState`.

**Comment by daniloercoli** [comment]
This is ready for another pass @0nko

File: aztec/src/main/kotlin/org/wordpress/aztec/source/SourceViewEditText.kt (hunk 2 above)
Comment (0nko) [reply aztec/src/main/kotlin/org/wordpress/aztec/source/SourceViewEditText.kt]: This is still a problem. If you switch to HTML, minimize and reopen the app the code is gone.

Comment (daniloercoli) [reply aztec/src/main/kotlin/org/wordpress/aztec/source/SourceViewEditText.kt]: Ohh 🤦‍♂️  Forgot to patch the HTML editor.

**Comment by 0nko** [comment]
Looks good 👍.
