### PR TITLE
Fix audio tag handling for Gutenberg audio blocks

### LINKED ISSUE #685: [Aztec + GB] <audio> tag gets converted to [audio] shortcode
### Expected
Gutenberg `audio` blocks  should remain unmodified

### Observed
When opening on Aztec, the `<audio>` tag gets converted into `[audio]` shortcode, breaking the Gutenberg block.

### Reproduced
1. Write a post on Gutenberg web, and include an `audio`-type block. The structure should be like this:

```
<!-- wp:audio -->
<figure class="wp-block-audio"><audio controls src="http://www.noiseaddicts.com/samples_1w72b820/4159.mp3"></audio></figure>
<!-- /wp:audio -->
```
2. Open it on the device
3. Now switch to HTML-mode
4. Observe the structure is now:
```
<!-- wp:audio -->
<figure class="wp-block-audio">
	[audio controls="controls" src="http://www.noiseaddicts.com/samples_1w72b820/4159.mp3"]</figure>
<!-- /wp:audio -->
```

Note: double checked Calypso mode on/off and it doesn't seem to affect the output.

#### Tested
[Google Pixel] on [8.0] with [1.3.4]

### PR DESCRIPTION
**Pull request by mzorz**
### Fix 
Fixes #685 as per the discussion in https://github.com/wordpress-mobile/WordPress-Android/pull/7826#issuecomment-393172951

The idea is that the plugin itself should be aware of Gutenberg blocks, and be able to differentiate and only apply itself to `<audio>` tags that are not within a Gutenberg block.

### Test
1. Feed Aztec with this HTML code, which is the Gutenberg code for an audio block:

```
<!-- wp:audio {"id":435} -->
<figure class="wp-block-audio"><audio controls src="http://www.noiseaddicts.com/samples_1w72b820/4159.mp3"></audio> <figcaption>
  a caption
 </figcaption></figure>
<!-- /wp:audio -->
```
or, create your own on Gutenberg.

2. Switch to visual mode
3. Now switch to HTML-mode
4. Observe the structure for the <audio> tag is preserved as <audio> (note the `controls="controls"` is expected and not harmful):
```
<!-- wp:audio {"id":435} --><figure class="wp-block-audio">
 <audio controls="controls" src="http://www.noiseaddicts.com/samples_1w72b820/4159.mp3"></audio>
 <figcaption>
  a caption
 </figcaption></figure><!-- /wp:audio -->
```

Also, test the same without the enclosing Gutenberg end/start tags:
```<figure class="wp-block-audio"><audio controls src="https://selfhostedmario.mystagingwebsite.com/wp-content/uploads/2018/05/ArgentinaAnthem.mp3"></audio><figcaption>a caption</figcaption></figure>```
In this case, the plugin should rightfully change the `<audio>` tags for `[audio]` shortcode, as expected.

**Note**: For easier review, please note the actual code change is in cfc512f, and tests have been added in  7178316, while instrumented tests have been added on 99d3efc.

### CODE REVIEW

File: app/src/androidTest/kotlin/org/wordpress/aztec/demo/tests/GutenbergCompatTests.kt [hunk 1]
```diff
@@ -289,6 +290,49 @@ class GutenbergCompatTests : BaseTest() {
...
+
+        val htmlWithShortcode = "<figure class=\"wp-block-audio\">\n" +
+                " [audio controls=\"controls\" src=\"https://selfhostedmario.mystagingwebsite.com/wp-content/uploads/2018/05/ArgentinaAnthem.mp3\"]\n" +
+                " <figcaption>\n" +
+                "  a caption\n" +
+                " </figcaption></figure>"
+
+        val editorPage = EditorPage()
+        val audioShortcodePlugin = AudioShortcodePlugin()
+        editorPage.getAztecText()?.plugins?.add(audioShortcodePlugin)
```
Comment (daniloercoli) [inline app/src/androidTest/kotlin/org/wordpress/aztec/demo/tests/GutenbergCompatTests.kt]: You can remove the code added to `EditorPage.kt` and here you can use:
```
val aztecText = mActivityIntentsTestRule.activity.findViewById<AztecText>(R.id.aztec)
aztecText.plugins?.add(audioShortcodePlugin)
```

**Comment by daniloercoli** [comment]
We can merge this PR once the feedback reported above is tackled .

**Comment by daniloercoli** [comment]
Looks good! :shipit:
